---
# getting all bash histories across all machines for different users into one file
# note: make sure others dont get access to the file as it may contain passwords and other secrets
- hosts: all
  gather_facts: no
  vars:
    users:
      - user
      - root

  tasks:
    - fetch:
        src: "~/.bash_history"
        dest: /tmp/all_history
      become: yes
      become_user: "{{ item }}"
      loop: "{{ users }}"

- hosts: localhost
  gather_facts: no
  tasks:
    - shell: 'find /tmp/all_history -type f -exec cat {} \;'
      register: all_history
      changed_when: false

    - file:
        path: /tmp/all_history
        state: absent

    - copy:
        content: "{{ all_history.stdout }}"
        dest: /root/all_history.txt
        force: yes
...
