---
# getting all bash histories across all machines for different users into one file
# note: make sure others dont get access to the file as it may contain passwords and other secrets
- hosts: all
  gather_facts: no
  vars:
    users:
      - user
      - root

  tasks:
    - fetch:
        src: "~/.bash_history"
        dest: /tmp/all_history
      become: yes
      become_user: "{{ item }}"
      loop: "{{ users }}"

- hosts: localhost
  gather_facts: no
  tasks:
    - find:
        path: /tmp/all_history/
        recurse: yes
        hidden: yes
      register: history_files

    - slurp:
        src: "{{ item.path }}"
      loop: "{{ history_files.files }}"
      register: all_history

    - file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/all_history/
        - /root/all_history.txt

    - blockinfile:
        marker: ''
        content: "{{ item.content | b64decode }}"
        dest: /root/all_history.txt
        create: yes
      loop: "{{ all_history.results }}"
...
