# updating hosts files on all machines
- hosts: all:!localhost
- hosts: all
  gather_facts: no
  tasks:
    - name: updating /etc/hosts
      blockinfile:
        dest: /etc/hosts
        block: "{{ lookup('template', 'hosts.j2') }}"
